### ISSUE TITLE
The stack data dump control is unreadable in Visual Studio Light theme

### ISSUE THREAD

**Issue by thoblerone** [Szpi/DumpStackToCSharpCode#6]
It is white text on light gray background, quite nasty to read.

The reason is that all controls use a forground property forcing them to be white:
Foreground="{DynamicResource {x:Static SystemColors.HighlightTextBrushKey}}"

Maybe a better choice woulde be {DynamicResource {x:Static vsshell:VsBrushes.ToolWindowTextKey}}

**Comment by Szpi** [comment]
Hello,
Thank you for the suggestion, now it also works on light ide theme.
You can download new version from vs marketplace.
